package com.ielts.allocate.mapper;

import com.ielts.allocate.entity.EngUser;
import java.util.List;

public interface EngUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eng_user
     *
     * @mbggenerated Wed Dec 25 20:55:33 CST 2019
     */
    EngUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eng_user
     *
     * @mbggenerated Wed Dec 25 20:55:33 CST 2019
     */
    List<EngUser> selectAll();
}