server:
  port: 8666
  tomcat:
    uri-encoding: utf-8
logging:
  level:
    com.wemedia: DEBUG
    tk.mybatis: ERROR
    org.springframework: ERROR
    file: log/allocate.log
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://101.132.103.111:3306/allocate?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    # 初始化大小，最小，最大
    initialSize: 1
    minIdle: 3
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    filters: stat,wall,slf4j
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
# classpath:mapper/*.xml 绑定
mybatis:
  type-aliases-package: com.ielts.allocate.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true