package com.ielts.allocate.entity;

import java.util.Date;

public class EngUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eng_user.id
     *
     * @mbggenerated Wed Dec 25 20:55:33 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eng_user.tel
     *
     * @mbggenerated Wed Dec 25 20:55:33 CST 2019
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eng_user.password
     *
     * @mbggenerated Wed Dec 25 20:55:33 CST 2019
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eng_user.salt
     *
     * @mbggenerated Wed Dec 25 20:55:33 CST 2019
     */
    private String salt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eng_user.wechat
     *
     * @mbggenerated Wed Dec 25 20:55:33 CST 2019
     */
    private String wechat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eng_user.taobao
     *
     * @mbggenerated Wed Dec 25 20:55:33 CST 2019
     */
    private String taobao;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eng_user.img
     *
     * @mbggenerated Wed Dec 25 20:55:33 CST 2019
     */
    private String img;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eng_user.nickname
     *
     * @mbggenerated Wed Dec 25 20:55:33 CST 2019
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eng_user.gender
     *
     * @mbggenerated Wed Dec 25 20:55:33 CST 2019
     */
    private Integer gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eng_user.examtype
     *
     * @mbggenerated Wed Dec 25 20:55:33 CST 2019
     */
    private Integer examtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eng_user.examdate
     *
     * @mbggenerated Wed Dec 25 20:55:33 CST 2019
     */
    private Date examdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eng_user.sign
     *
     * @mbggenerated Wed Dec 25 20:55:33 CST 2019
     */
    private Integer sign;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eng_user.basic
     *
     * @mbggenerated Wed Dec 25 20:55:33 CST 2019
     */
    private Double basic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eng_user.target
     *
     * @mbggenerated Wed Dec 25 20:55:33 CST 2019
     */
    private Double target;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eng_user.create_time
     *
     * @mbggenerated Wed Dec 25 20:55:33 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eng_user.update_time
     *
     * @mbggenerated Wed Dec 25 20:55:33 CST 2019
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eng_user.last_login_time
     *
     * @mbggenerated Wed Dec 25 20:55:33 CST 2019
     */
    private Date lastLoginTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eng_user.id
     *
     * @return the value of eng_user.id
     *
     * @mbggenerated Wed Dec 25 20:55:33 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eng_user.id
     *
     * @param id the value for eng_user.id
     *
     * @mbggenerated Wed Dec 25 20:55:33 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eng_user.tel
     *
     * @return the value of eng_user.tel
     *
     * @mbggenerated Wed Dec 25 20:55:33 CST 2019
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eng_user.tel
     *
     * @param tel the value for eng_user.tel
     *
     * @mbggenerated Wed Dec 25 20:55:33 CST 2019
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eng_user.password
     *
     * @return the value of eng_user.password
     *
     * @mbggenerated Wed Dec 25 20:55:33 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eng_user.password
     *
     * @param password the value for eng_user.password
     *
     * @mbggenerated Wed Dec 25 20:55:33 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eng_user.salt
     *
     * @return the value of eng_user.salt
     *
     * @mbggenerated Wed Dec 25 20:55:33 CST 2019
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eng_user.salt
     *
     * @param salt the value for eng_user.salt
     *
     * @mbggenerated Wed Dec 25 20:55:33 CST 2019
     */
    public void setSalt(String salt) {
        this.salt = salt == null ? null : salt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eng_user.wechat
     *
     * @return the value of eng_user.wechat
     *
     * @mbggenerated Wed Dec 25 20:55:33 CST 2019
     */
    public String getWechat() {
        return wechat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eng_user.wechat
     *
     * @param wechat the value for eng_user.wechat
     *
     * @mbggenerated Wed Dec 25 20:55:33 CST 2019
     */
    public void setWechat(String wechat) {
        this.wechat = wechat == null ? null : wechat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eng_user.taobao
     *
     * @return the value of eng_user.taobao
     *
     * @mbggenerated Wed Dec 25 20:55:33 CST 2019
     */
    public String getTaobao() {
        return taobao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eng_user.taobao
     *
     * @param taobao the value for eng_user.taobao
     *
     * @mbggenerated Wed Dec 25 20:55:33 CST 2019
     */
    public void setTaobao(String taobao) {
        this.taobao = taobao == null ? null : taobao.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eng_user.img
     *
     * @return the value of eng_user.img
     *
     * @mbggenerated Wed Dec 25 20:55:33 CST 2019
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eng_user.img
     *
     * @param img the value for eng_user.img
     *
     * @mbggenerated Wed Dec 25 20:55:33 CST 2019
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eng_user.nickname
     *
     * @return the value of eng_user.nickname
     *
     * @mbggenerated Wed Dec 25 20:55:33 CST 2019
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eng_user.nickname
     *
     * @param nickname the value for eng_user.nickname
     *
     * @mbggenerated Wed Dec 25 20:55:33 CST 2019
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eng_user.gender
     *
     * @return the value of eng_user.gender
     *
     * @mbggenerated Wed Dec 25 20:55:33 CST 2019
     */
    public Integer getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eng_user.gender
     *
     * @param gender the value for eng_user.gender
     *
     * @mbggenerated Wed Dec 25 20:55:33 CST 2019
     */
    public void setGender(Integer gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eng_user.examtype
     *
     * @return the value of eng_user.examtype
     *
     * @mbggenerated Wed Dec 25 20:55:33 CST 2019
     */
    public Integer getExamtype() {
        return examtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eng_user.examtype
     *
     * @param examtype the value for eng_user.examtype
     *
     * @mbggenerated Wed Dec 25 20:55:33 CST 2019
     */
    public void setExamtype(Integer examtype) {
        this.examtype = examtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eng_user.examdate
     *
     * @return the value of eng_user.examdate
     *
     * @mbggenerated Wed Dec 25 20:55:33 CST 2019
     */
    public Date getExamdate() {
        return examdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eng_user.examdate
     *
     * @param examdate the value for eng_user.examdate
     *
     * @mbggenerated Wed Dec 25 20:55:33 CST 2019
     */
    public void setExamdate(Date examdate) {
        this.examdate = examdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eng_user.sign
     *
     * @return the value of eng_user.sign
     *
     * @mbggenerated Wed Dec 25 20:55:33 CST 2019
     */
    public Integer getSign() {
        return sign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eng_user.sign
     *
     * @param sign the value for eng_user.sign
     *
     * @mbggenerated Wed Dec 25 20:55:33 CST 2019
     */
    public void setSign(Integer sign) {
        this.sign = sign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eng_user.basic
     *
     * @return the value of eng_user.basic
     *
     * @mbggenerated Wed Dec 25 20:55:33 CST 2019
     */
    public Double getBasic() {
        return basic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eng_user.basic
     *
     * @param basic the value for eng_user.basic
     *
     * @mbggenerated Wed Dec 25 20:55:33 CST 2019
     */
    public void setBasic(Double basic) {
        this.basic = basic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eng_user.target
     *
     * @return the value of eng_user.target
     *
     * @mbggenerated Wed Dec 25 20:55:33 CST 2019
     */
    public Double getTarget() {
        return target;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eng_user.target
     *
     * @param target the value for eng_user.target
     *
     * @mbggenerated Wed Dec 25 20:55:33 CST 2019
     */
    public void setTarget(Double target) {
        this.target = target;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eng_user.create_time
     *
     * @return the value of eng_user.create_time
     *
     * @mbggenerated Wed Dec 25 20:55:33 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eng_user.create_time
     *
     * @param createTime the value for eng_user.create_time
     *
     * @mbggenerated Wed Dec 25 20:55:33 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eng_user.update_time
     *
     * @return the value of eng_user.update_time
     *
     * @mbggenerated Wed Dec 25 20:55:33 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eng_user.update_time
     *
     * @param updateTime the value for eng_user.update_time
     *
     * @mbggenerated Wed Dec 25 20:55:33 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eng_user.last_login_time
     *
     * @return the value of eng_user.last_login_time
     *
     * @mbggenerated Wed Dec 25 20:55:33 CST 2019
     */
    public Date getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eng_user.last_login_time
     *
     * @param lastLoginTime the value for eng_user.last_login_time
     *
     * @mbggenerated Wed Dec 25 20:55:33 CST 2019
     */
    public void setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }
}